name: updateEPG
on:
  schedule:
    - cron: '0 2 * * *'  # 每天凌晨 2 点运行

jobs:
  updateEPG:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Clone repository
        run: git clone https://github.com/doube-ba/TWEPG.git

      - name: Install dependencies
        working-directory: ./TWEPG
        run: pip install -r requirements.txt

      - name: Run Python script
        working-directory: ./TWEPG
        run: |
          echo "Running Python script..."
          python twEPG.py
          echo "Python script completed."

      - name: Configure Git
        run: |
          git config --global user.email "doubebly@gmail.com"
          git config --global user.name "doubebly"

      - name: Add and commit changes
        working-directory: ./TWEPG
        run: |
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Automated update by GitHub Actions"
          else
            echo "No changes to commit."
          fi

      - name: Push changes
        working-directory: ./TWEPG
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git push https://${TOKEN}@github.com/doube-ba/TWEPG.git main
          else
            echo "No changes to push."
          fi
